#!/usr/bin/env bash
# =============================================================================
# todo-commit.sh — generate a commit message from the "✅ Fait" section of
# TODO.md, then strip those entries.
#
# Wired into prek as a `prepare-commit-msg` hook (see prek.toml): on a plain
# `git commit`, it pre-fills the commit editor with a Conventional Commits
# message derived from the done entries, removes them from TODO.md and
# re-stages the file so the cleanup lands in the same commit. You still
# review/edit the message in the editor before the commit completes.
#
# The message is generated by the `claude` CLI (headless `claude -p`) from the
# ✅ Fait entries; if the CLI is missing/offline/disabled it falls back to a
# deterministic message built from the same entries. Env knobs:
#   TODO_COMMIT_NO_AI=1            force the deterministic generator (no LLM)
#   TODO_COMMIT_CLAUDE_MODEL=...   model for `claude -p` (default: sonnet)
#   TODO_COMMIT_AI_TIMEOUT=secs    cap the AI call (default 60, needs timeout(1))
#
# Subcommands (also used by tests/todo-commit.bats):
#   todo-commit.sh message [TODO.md]   print the deterministic commit message
#   todo-commit.sh ai      [TODO.md]   print the AI-generated message (claude -p)
#   todo-commit.sh strip   [TODO.md]   remove "✅ Fait" entries in place
#   todo-commit.sh hook <msgfile> <source> <sha>   prepare-commit-msg entry
#
# Re-staging relies on `git commit` building the commit from the real index
# (the normal `git add` then `git commit` flow, and `git commit -a`). A partial
# commit (`git commit <pathspec>`, `-o`/`--only`) builds from a temporary index
# the hook can't re-stage into, so the hook detects that (GIT_INDEX_FILE points
# at a non-default index) and does nothing — no pre-fill, no strip — rather than
# leaving the strip stranded in the working tree.
# =============================================================================
set -euo pipefail

FAIT_HEADING='## ✅ Fait'

# Print the raw "- [x] ..." lines under the ✅ Fait section of $1.
fait_entries() {
  awk -v h="$FAIT_HEADING" '
    $0 == h { infait=1; next }
    /^## /  { infait=0 }
    infait && /^- \[x\] / { print }
  ' "$1"
}

# Lowercase a TODO TYPE and drop any "(URGENT)" marker → conventional type.
conv_type() {
  local t="${1%%(*}"
  printf '%s' "$t" | tr '[:upper:]' '[:lower:]'
}

# Parse one "- [x] 2026-06-17 — FIX: description" line into "TYPE<TAB>DESC".
parse_entry() {
  local line="$1"
  line="${line#- \[x\] }"
  # drop a leading "YYYY-MM-DD — " date stamp if present
  line="$(printf '%s' "$line" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2} +— +//')"
  local type="${line%%:*}"
  local desc="${line#*: }"
  printf '%s\t%s' "$type" "$desc"
}

# Build a commit message from the Fait entries of $1. Returns 1 if none.
generate_message() {
  local entries; entries="$(fait_entries "$1")"
  [ -z "$entries" ] && return 1

  local ftype fdesc
  IFS=$'\t' read -r ftype fdesc <<<"$(parse_entry "$(printf '%s\n' "$entries" | head -n1)")"
  printf '%s: %s\n' "$(conv_type "$ftype")" "$fdesc"

  local n; n="$(printf '%s\n' "$entries" | grep -c '.' || true)"
  if [ "$n" -gt 1 ]; then
    printf '\n'
    local line t d
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      IFS=$'\t' read -r t d <<<"$(parse_entry "$line")"
      printf -- '- %s: %s\n' "$(conv_type "$t")" "$d"
    done <<<"$entries"
  fi
}

# Generate a commit message from the Fait entries of $1 via the `claude` CLI
# (headless `claude -p`). Prints the message to stdout. Returns non-zero on any
# problem (CLI missing, disabled, no entries, timeout, error, empty output) so
# the caller can fall back to the deterministic generate_message.
#
# Env knobs: TODO_COMMIT_NO_AI=1 disables it; TODO_COMMIT_CLAUDE_MODEL overrides
# the model (default: sonnet); TODO_COMMIT_AI_TIMEOUT caps the call (default 60s,
# only enforced when `timeout`/`gtimeout` is available).
generate_message_ai() {
  local todo="$1"
  [ "${TODO_COMMIT_NO_AI:-0}" = "1" ] && return 1
  command -v claude >/dev/null 2>&1 || return 1

  local entries; entries="$(fait_entries "$todo")"
  [ -z "$entries" ] && return 1

  # Single-quoted instructions + variable concatenation: never let a heredoc
  # evaluate the backticks/$ that appear inside the Fait entries.
  local instructions prompt
  instructions='Write ONE git commit message in Conventional Commits format that summarizes the completed tasks below.
Rules:
- First line: a concise "<type>: summary" header, max ~72 chars (types: feat, fix, docs, chore, refactor, test).
- Then a blank line, then a "- " bullet body, one bullet per meaningful change.
- Group related tasks; keep it clean and structured. Do not invent changes.
- Output ONLY the raw commit message: no markdown code fences, no preamble, no quotes, no trailing commentary.

Completed tasks:'
  prompt="$instructions
$entries"

  # Keep the call lean for a commit hook: --strict-mcp-config skips loading the
  # project's MCP servers (the slow part of startup); the prompt is self-contained
  # so no tools are needed. OAuth/keychain auth still applies.
  local -a runner=(claude -p "$prompt" --model "${TODO_COMMIT_CLAUDE_MODEL:-sonnet}" --strict-mcp-config)
  local out
  if command -v timeout >/dev/null 2>&1; then
    out="$(timeout "${TODO_COMMIT_AI_TIMEOUT:-60}" "${runner[@]}" 2>/dev/null)" || return 1
  elif command -v gtimeout >/dev/null 2>&1; then
    out="$(gtimeout "${TODO_COMMIT_AI_TIMEOUT:-60}" "${runner[@]}" 2>/dev/null)" || return 1
  else
    out="$("${runner[@]}" 2>/dev/null)" || return 1
  fi

  # Drop any stray code-fence lines and leading blank lines.
  out="$(printf '%s\n' "$out" | grep -v '^[[:space:]]*```' | awk 'NF{p=1} p')"
  [ -n "$out" ] || return 1
  printf '%s\n' "$out"
}

# Remove every "- [x] ..." entry under the ✅ Fait section of $1 (in place).
strip_done() {
  local tmp; tmp="$(mktemp "${1}.XXXXXX")"
  awk -v h="$FAIT_HEADING" '
    $0 == h { infait=1; print; next }
    /^## /  { infait=0 }
    infait && /^- \[x\] / { next }
    { print }
  ' "$1" > "$tmp"
  mv "$tmp" "$1"
}

# True when git is committing from a temporary index — i.e. a partial commit
# (`git commit <pathspec>`, `-o`/`--only`). git points GIT_INDEX_FILE at a temp
# index (e.g. .git/next-index-<pid>) and builds the commit from it, so a
# `git add` from this hook touches the real index, not the one being committed —
# the strip would land in the working tree but not the commit. Treat any
# non-default index as "don't touch", so the hook is a no-op there.
is_temp_index() {
  [ -n "${GIT_INDEX_FILE:-}" ] || return 1   # unset → normal full commit
  local gitdir; gitdir="$(git rev-parse --git-dir 2>/dev/null)" || return 1
  case "$GIT_INDEX_FILE" in
    index|"$gitdir/index"|"$(git rev-parse --absolute-git-dir 2>/dev/null)/index") return 1 ;;
    *) return 0 ;;
  esac
}

# TEMP DEBUG — appends one line per event to .git/todo-commit-debug.log so we can
# see what happens during a VS Code commit. Remove once diagnosed.
_dbg() {
  local gd; gd="$(git rev-parse --git-dir 2>/dev/null)" || return 0
  printf '%s | %s\n' "$(date '+%F %T' 2>/dev/null)" "$*" >> "$gd/todo-commit-debug.log" 2>/dev/null || true
}

# prepare-commit-msg entry point: $1 msg file, $2 source, $3 sha.
run_hook() {
  local msgfile="$1" source="${2:-}"
  _dbg "RUN source='$source' msgfile='$msgfile' GIT_INDEX_FILE='${GIT_INDEX_FILE:-}' PATH=$PATH"
  # Only act on a plain commit: skip -m/-F (message), -t (template), merge,
  # squash and amend, which all pass a non-empty source.
  [ -n "$source" ] && { _dbg "SKIP: non-empty source ('$source')"; return 0; }
  [ -n "$msgfile" ] && [ -f "$msgfile" ] || { _dbg "SKIP: missing msgfile"; return 0; }
  # Don't clobber an existing message. prek may not forward `source`, so guard on
  # content too: if the file already has a non-blank, non-comment line (e.g.
  # `git commit -m`, a -t template, an amend), leave it untouched.
  if grep -qvE '^[[:space:]]*(#|$)' "$msgfile"; then _dbg "SKIP: msgfile already has content"; return 0; fi
  # Skip partial commits (`git commit <pathspec>` / -o): we can't reliably
  # land the TODO.md strip in such a commit, so don't pre-fill or strip either.
  is_temp_index && { _dbg "SKIP: temp index (partial commit)"; return 0; }

  local repo_root; repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || { _dbg "SKIP: no repo root"; return 0; }
  local todo="$repo_root/TODO.md"
  [ -f "$todo" ] || { _dbg "SKIP: no TODO.md at $todo"; return 0; }
  _dbg "todo=$todo claude=$(command -v claude || echo MISSING) NO_AI=${TODO_COMMIT_NO_AI:-0}"

  # Prefer a Claude-generated message; fall back to the deterministic one when
  # the CLI is unavailable/offline/disabled. Either way, no entries → no-op.
  local msg
  if msg="$(generate_message_ai "$todo")"; then _dbg "msg: AI ok (${#msg} chars)"
  elif msg="$(generate_message "$todo")"; then _dbg "msg: deterministic fallback (${#msg} chars)"
  else _dbg "SKIP: no Fait entries → no-op"; return 0; fi

  # Prepend the generated message above git's commented template.
  local tmp; tmp="$(mktemp "${msgfile}.XXXXXX")"
  { printf '%s\n' "$msg"; cat "$msgfile"; } > "$tmp"
  mv "$tmp" "$msgfile"

  # Consume the entries and re-stage TODO.md so the cleanup is in this commit.
  strip_done "$todo"
  git add -- "$todo" 2>/dev/null || true
  _dbg "DONE: pre-filled msg + stripped/re-staged TODO.md"
}

main() {
  local cmd="${1:-}"; shift || true
  case "$cmd" in
    message) generate_message "${1:-TODO.md}" ;;
    ai)      generate_message_ai "${1:-TODO.md}" ;;
    strip)   strip_done "${1:-TODO.md}" ;;
    hook)    run_hook "${1:-}" "${2:-}" "${3:-}" ;;
    *) echo "usage: todo-commit.sh {message|ai|strip|hook} [args...]" >&2; exit 2 ;;
  esac
}

main "$@"
